### PR TITLE
make environment.rb a template

### PR DESCRIPTION
**Pull request by dunn**
See https://github.com/acozine/sufia-centos/pull/41#discussion_r52035440

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you explain why you think this change is necessary?  Removing `config/environment.rb` is not something that's usually done.

**Comment by dunn** [comment]
From the comment I linked to:
> I want to replace environment.rb with a .template in ADRL. I've found `Rails.env = ENV['RAILS_ENV'] || '{{ rails_env }}'` really useful in keeping the environment consistent without having to remember to set RAILS_ENV for basic things like `rails console`.

With this change the environment is automatically set to the correct value for not just `console` but all the ingest scripts as well. It only needs to be overridden for running the tests and that can be part of the Rake task.

**Comment by jcoyne** [comment]
@dunn Why don't you just set `export RAILS_ENV=production` in your .bashrc?

**Comment by dunn** [comment]
On my local machine, I don't want `RAILS_ENV` set unconditionally, since I might want difference environments for different projects.  On Vagrant and in production, setting it in `.bashrc` or `/etc/environment` will probably make debugging harder since someone new to the project won't know where `RAILS_ENV` is getting set.

**Comment by jcoyne** [comment]
config/environment.rb is executed rather late in the startup process and I'm concerned that by relying on it you introduce subtle failures.  Have you checked that ENV["RACK_ENV"] gets set correctly when use use this method?  The Rack middleware depends on the environment being passed to it by Rails::Server.  I'm pretty sure that happens before `config/environment.rb` is called. If you don't have the correct middleware stack initialized, you could expose yourself to security vulnerabilities.

**Comment by dunn** [comment]
Gotcha, I'll drop this idea then.

**Pull request closed without merging**
