### PR TITLE
[css] commits from GH Enterprise

### PR DESCRIPTION
**Pull request by dunn**
The major change in this set of commits is the responsive homepage.  Other changes focus on simplifying the CSS; if anything is unexplained by the commit messages let me know.

### CODE REVIEW

**Comment by dunn** [comment]
Some of these changes appeared originally in https://github.library.ucsb.edu/ADRL/alexandria/pull/1 and https://github.library.ucsb.edu/ADRL/alexandria/pull/4

**Comment by jcoyne** [comment]
I deployed this branch to http://ucsb.curationexperts.com/  Testing now.

**Comment by jcoyne** [comment]
Testing on Firefox. My concerns:

White dots have high contrast in menu:
screen shot 2016-02-11 at 6 53 04 pm

Labels are cut off with elipsis:
screen shot 2016-02-11 at 6 54 22 pm

Left side corners are not round.  White gap between select and search field.
screen shot 2016-02-11 at 6 54 37 pm

These links look disabled, but they're not:
screen shot 2016-02-11 at 6 54 57 pm

**Comment by jcoyne** [comment]
screen shot 2016-02-11 at 6 57 56 pm
Too much padding on the left side

**Comment by jcoyne** [comment]
screen shot 2016-02-11 at 6 59 03 pm
Buttons do not line up with fields.

**Comment by dunn** [comment]
> Buttons do not line up with fields.

Which view(s)?

**Comment by jcoyne** [comment]
The field line up is on this page: http://ucsb.curationexperts.com/records/new?utf8=%E2%9C%93&type=Image&commit=Next  Specifically for Language, Institution and Rights Holder

**Comment by dunn** [comment]
> White dots have high contrast in menu

That was intentional, to help separate the menu items visually.  I'm fine changing it, but having them the same gray as the text didn't work, in my opinion.

I think I fixed everything else.

**Pull request merged**
