### PR TITLE
Associate supplemental files with existing etd. Fixes #267

### LINKED ISSUE #267: Associate supplemental file(s) with existing ETDs
Extend the existing ETD file import to attach any supplemental files included in the proquest zip file 

**GIVENS**
* There will be an existing ETD object that has a system ID, title, creator, and primary filename
* Downloads will be in a server directory "#{downloads_root}/etd/proquest"
* Supplemental files will be embedded in a zip file with a name in the format:  etdadmin_upload_331128.zip
* Valid files for import must contain
    * at least one PDF matching the primary file name 
    * at least one XML file matching the primary file name
* if the zip file contains a subdirectory, attach the files in the subdirectory to the ETD object
* Importer runs from the command line in the foreground for the time being

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mark-dce** [comment]
FYI - When I checkout this branch and try to run the importer locally as follows:
```bash
bundle exec traject -c traject_config.rb ~/Google\ Drive/DCE\ Clients/UC\ Santa\ Barbara/Sample\ Data/opt/download_root/marc/004511621.xml
```

I get the following error
```text
2015-07-07T00:00:33-05:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<ActiveFedora::UnknownAttributeError: ETD does not have an attribute `keyword_ssim'>
```

All specs run green on my system.  So, basically the issue is that I can't import 004511621.xml.  I *can* import 004511717.xml successfully, so we could either merge this PR and copy this info to a bug report or hold off on the PR and fix whatever is going on here first.

**SAMPLE DATA**
System Number = 004511621
marc file = 004511621.xml
ARK = 48907/fake1     *<-- yes, this is a made-up ark*
proquest file =  Murray_ucsb_0035D_12159.pdf

**PROQUEST CONTENTS**
```text
+----- Murray_ucsb_0035D_12159_DATA.xml
+----- Murray_ucsb_0035D_12159.pdf
+----- Murray_ucsb_0035D_67
         +----- SupplementalFile1.pdf      <-- yes, these are the real filenames in the zip archive
         +----- SupplementalFile2.pdf
         +----- SupplementalFile2.pdf
 ```

**Comment by mark-dce** [comment]
For MARC files, I can import, this only finds ETD zip files if they're in the same directory I run the importer from - i.e. the importer doesn't seem to be searching in download_root/proquest

**Comment by jcoyne** [comment]
The keyword issue should be resolved by #294

**Comment by jcoyne** [comment]
Searching for zips in the download directory should be fixed by #287

**Pull request merged**
