### PR TITLE
sets ownership of metadata dir for clone step

### PR DESCRIPTION
**Pull request by acozine**

### CODE REVIEW

**Comment by acozine** [comment]
@dunn this seems uncontroversial - can you give it a thumbs-up/thumbs-down review?

**Comment by dunn** [comment]
Ingests will be performed by the `deploy_user`, so as long as they still have read access this seems fine.

**Comment by acozine** [comment]
@dunn - that still happens in line 19 below - this change is a fix for the permissions errors I was seeing when Ansible tried to clone the code

**Comment by dunn** [comment]
Then :+1:

**Pull request merged**
